#!/bin/bash


export CLUSTER_NAME=cafecluster

# Bootstrapper and Master
export BLACKSMITH_BOOTSTRAPPER1_HOSTNAME=bootstrapper1
export BLACKSMITH_BOOTSTRAPPER1_IP=192.168.64.11
export BLACKSMITH_BOOTSTRAPPER1_INTERNAL_INTERFACE_NAME=eno1

# Bootstrapper but Worker
export BLACKSMITH_BOOTSTRAPPER2_HOSTNAME=bootstrapper2
export BLACKSMITH_BOOTSTRAPPER2_IP=192.168.64.12
export BLACKSMITH_BOOTSTRAPPER2_INTERNAL_INTERFACE_NAME=eno1

# Bootstrapper but Worker
export BLACKSMITH_BOOTSTRAPPER3_HOSTNAME=bootstrapper3
export BLACKSMITH_BOOTSTRAPPER3_IP=192.168.64.13
export BLACKSMITH_BOOTSTRAPPER3_INTERNAL_INTERFACE_NAME=eno1

export INTERNAL_NETWORK_GATEWAY_IP=192.168.64.1
export INTERNAL_NETWORK_NETSIZE=20
export EXTERNAL_DNS=8.8.8.8
export INTERNAL_NETWORK_WORKERS_START=192.168.65.1
export INTERNAL_NETWORK_WORKERS_LIMIT=3580

export POD_NETWORK=10.1.0.0/16
export SERVICE_IP_RANGE=10.100.0.0/16
export K8S_SERVICE_IP=10.100.0.1
export DNS_SERVICE_IP=10.100.0.10

export CERT_ARGS=

export CONTEXT_NAME=default-context

export K8S_VER=v1.2.4_coreos.1
export HYPERKUBE_IMAGE=quay.io/coreos/hyperkube:$K8S_VER
export BLACKSMITH_IMAGE=cafebazaar/blacksmith:v0.9.1
export SKYDNS_IMAGE=quay.io/cafebazaar/skydns:2.5.3a-39-ge18ede9

export ADMIN_PKCS12_PASSWORD=ChangeMe

export HTTP_PROXY=
export HTTPS_PROXY=
export NO_PROXY="localhost,127.0.0.1,.$CLUSTER_NAME,$BLACKSMITH_BOOTSTRAPPER1_IP,$BLACKSMITH_BOOTSTRAPPER2_IP,$BLACKSMITH_BOOTSTRAPPER3_IP"
