apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: colonelmo/hyperkube
    command:
    - /hyperkube
    - controller-manager
    - --cluster-name=default-cluster
    - --master=http://192.168.60.101:8080
    - --service-account-private-key-file=/srv/kubernetes/server.key
    - --root-ca-file=/srv/kubernetes/ca.crt
    volumeMounts:
    - mountPath: /srv/kubernetes
      name: srvkube
      readOnly: true
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
  volumes:
  - hostPath:
      path: /srv/kubernetes
    name: srvkube
  - hostPath:
      path: /etc/ssl
    name: etcssl
