apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: ${BLACKSMITH_HYPERKUBE_IMAGE}
    command:
    - /hyperkube
    - controller-manager
    - --cluster-name=${CLUSTER_NAME}
    - --master=http://${BLACKSMITH_BOOTSTRAPPER1_IP}:8080
    - --service-account-private-key-file=${MASTER_KEY}
    - --root-ca-file=${CA_CERT}
    volumeMounts:
    - mountPath: /srv/kubernetes
      name: srvkube
      readOnly: true
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
  volumes:
  - hostPath:
      path: /srv/kubernetes
    name: srvkube
  - hostPath:
      path: /etc/ssl
    name: etcssl
