
    - name: etcd2.service
      command: start
    
    - name: flanneld.service
      command: start
      drop-ins:
      - name: 40-network-config.conf
        content: |
          [Service]
          ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env
          ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"<< (cluster_variable "pod_network") >>", "Backend": {"Type": "vxlan"}}'
    - name: update-engine.service
      drop-ins:
        - name: 50-proxy.conf
          content: |
            [Service]
            Environment="HTTP_PROXY=<< (cluster_variable "http_proxy") >>"
            Environment="HTTPS_PROXY=<< (cluster_variable "https_proxy") >>"
            Environment="NO_PROXY=localhost,127.0.0.1,.<< (cluster_variable "cluster_name") >>,<< (cluster_variable "bootstrapper1_ip") >>,<< (cluster_variable "bootstrapper2_ip") >>,<< (cluster_variable "bootstrapper3_ip") >>"
      command: restart
    - name: 10-static.network
      runtime: true
      content: |
        [Match]
        Name=<<(machine_variable "external_interface_name")>>

        [Network]
        DHCP=no    
        Address=<< (machine_variable "external_ip") >>/22   
        DNS=<< (cluster_variable "bootstrapper1_ip" )>>
        DNS=<< (cluster_variable "external_dns") >>
        Gateway=<< (cluster_variable "gateway") >>

    - name: docker.service
      command: start
      drop-ins:
        - name: 20-http-proxy.conf
          content: |
            [Service]
            Environment="HTTP_PROXY=<< (cluster_variable "http_proxy") >>"
            Environment="HTTPS_PROXY=<< (cluster_variable "https_proxy") >>"
            <<wi")>><< if $address | ne "" >>Environment="DOCKER_OPTS=--insecure-registry << $address >>"<< end >><<end>>
            Environment="NO_PROXY=localhost,127.0.0.1,.<< (cluster_variable "cluster_name") >>,<< (cluster_variable "bootstrapper1_ip") >>,<< (cluster_variable "bootstrapper2_ip") >>,<< (cluster_variable "bootstrapper3_ip") >>"
        - name: 50-flanneld.conf
          content: |
            [Unit]
            After=flanneld.service
            Requires=flanneld.service
    - name: workspace-updater.service
      command: start
      content: |
        [Unit]
        Description=Blacksmith Kubernetes Workspace Updater
        Documentation=https://github.com/cafebazaar/blacksmith-kubernetes
        [Service]
        ExecStartPre=curl -o /var/lib/blacksmith/workspace-updater.sh http://master.cafecluster:8000/api/render/?path=workspace-updater.sh&mac=<<.Mac>>
        ExecStart=/usr/bin/bash /var/lib/blacksmith/workspace-updater.sh
        Restart=always
        RestartSec=10
        [Install]
        WantedBy=multi-user.target
