
    - name: 00-{{ (machine_variable "external_interface_name") }}.network
      runtime: true
      content: |
        [Match]
        Name={{ (machine_variable "external_interface_name") }}

        [Network]
        Address={{ (machine_variable "external_ip") }}/{{(cluster_variable "external_network_netsize")}}
        Gateway={{ (cluster_variable "gateway") }}
    - name: etcd2.service
      command: start
    
    - name: flanneld.service
      command: start
      drop-ins:
      - name: 40-network-config.conf
        content: |
          [Service]
          ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env
          ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"{{ (cluster_variable "pod_network") }}", "Backend": {"Type": "vxlan"}}'
    - name: update-engine.service
      drop-ins:
        - name: 50-proxy.conf
          content: |
            [Service]
            Environment="HTTP_PROXY={{ (cluster_variable "http_proxy") }}"
            Environment="HTTPS_PROXY={{ (cluster_variable "https_proxy") }}"
            Environment="NO_PROXY=localhost,127.0.0.1,.{{ (blacksmith_variable "cluster_name") }},{{ (cluster_variable "bootstrapper1_ip") }},{{ (cluster_variable "bootstrapper2_ip") }},{{ (cluster_variable "bootstrapper3_ip") }}"
      command: restart
    - name: docker.service
      command: start
      drop-ins:
        - name: 10-proxy.conf
          content: |
            [Service]
            Environment="HTTP_PROXY={{ (cluster_variable "http_proxy") }}"
            Environment="HTTPS_PROXY={{ (cluster_variable "https_proxy") }}"
            Environment="NO_PROXY=localhost,127.0.0.1,.{{ (blacksmith_variable "cluster_name") }},{{ (cluster_variable "bootstrapper1_ip") }},{{ (cluster_variable "bootstrapper2_ip") }},{{ (cluster_variable "bootstrapper3_ip") }}"
            Environment=DOCKER_OPTS='--insecure-registry="172.19.1.1/24"'
      drop-ins:
        - name: 50-flanneld.conf
          content: |
            [Unit]
            After=flanneld.service
            Requires=flanneld.service
