cluster-variables:
<< range $index, $element := (array_variable "cluster-variables") >>  << $element.Key | pathSplit >>: '<<$element.Value>>'
<<end>>
machines:
<< range $index, $element := (array_variable "machines") >><<if ne ($element.Key | pathSplit) ("0a0027000000")>>  <<$element.Key | pathSplit>>:
  << range $index1, $element1 := $element.Nodes >>    << $element1.Key | pathSplit >>: '<<$element1.Value>>'
  <<end>>    _machine: '{"ip":"","first_seen":0,"type":1}'
<<end>>
<<end>>

ssh-keys:
<< range $index, $element := (array_variable "ssh-keys") >>  - << $element.Key | pathSplit >>: '<<$element.Value>>'
<<end>>
