apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: {{ (cluster_variable "hyperkube_image") }}
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --etcd-servers=http://{{ (cluster_variable "bootstrapper1_ip") }}:4001,http://{{ (cluster_variable "bootstrapper2_ip") }}:4001,http://{{ (cluster_variable "bootstrapper3_ip") }}:4001
    - --allow-privileged=true
    - --service-cluster-ip-range={{ (cluster_variable "service_ip_range") }}
    - --secure-port=4443
    - --advertise-address={{ (cluster_variable "bootstrapper1_ip") }}
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --runtime-config=api/all=true
    - --authorization-mode=RBAC
    - --authorization-rbac-super-user=admin
    - --oidc-issuer-url=https://k8s.roo.cloud:32000/dex
    - --oidc-client-id=cafecluster-dex-app
    - --oidc-username-claim=email
    - --oidc-groups-claim=groups
    ports:
    - containerPort: 4443
      hostPort: 4443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
