    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/kubernetes/kubernetes
        [Service]
        Environment=KUBELET_VERSION={{ (cluster_variable "k8s_version") }}
        ExecStartPre=-/usr/bin/mkdir -p /var/log/containers
        Environment="RKT_OPTS=--volume=resolv,kind=host,source=/etc/resolv.conf --mount volume=resolv,target=/etc/resolv.conf --volume var-log,kind=host,source=/var/log --mount volume=var-log,target=/var/log --volume modprobe,kind=host,source=/usr/sbin/modprobe \--mount volume=modprobe target=/usr/sbin/modprobe --volume lib-modules,kind=host,source=/lib/modules --mount volume=lib-modules,target=/lib/modules"
        Environment="HTTP_PROXY={{ (cluster_variable "http_proxy") }}"
        Environment="HTTPS_PROXY={{ (cluster_variable "https_proxy") }}"
        Environment="NO_PROXY=localhost,127.0.0.1,.{{ (cluster_variable "cluster_name") }},{{ (cluster_variable "bootstrapper1_ip") }},{{ (cluster_variable "bootstrapper2_ip") }},{{ (cluster_variable "bootstrapper3_ip") }}"
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --api-servers=http://127.0.0.1:8080 \
          --register-schedulable=true \
          --allow-privileged=true \
          --config=/etc/kubernetes/manifests \
          --cluster-dns={{(cluster_variable "dns_server_ip")}} \
          --cluster-domain={{(cluster_variable "cluster_name")}}
        Restart=always
        RestartSec=10
        [Install]
        WantedBy=multi-user.target

    - name: install-bootstrapper.service
      command: start
      content: |
        [Unit]
        Description=Initializes the machine
        Requires=docker.service
        After=etcd.service etcd2.service docker.service

        [Service]
        Type=oneshot
        ExecStart=/tmp/install-bootstrapper.sh {{(machine_variable "internal_interface_name")}}

        [Install]
        WantedBy=multi-user.target
