write_files:
{{template "common-files.yaml" .}}
{{template "worker-files.yaml" .}}

coreos:
  etcd2:
    proxy: on
    initial-cluster: {{.EtcdEndpoints}}
    listen-client-urls: http://127.0.0.1:2379,http://127.0.0.1:4001
  update:
    reboot-strategy: etcd-lock
  units:
{{template "common-units.yaml" .}}
    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/kubernetes/kubernetes
        [Service]
        Environment=KUBELET_VERSION={{ (cluster_variable "k8s_version") }}
        ExecStartPre=-/usr/bin/mkdir -p /var/log/containers
        Environment="RKT_OPTS=--volume=resolv,kind=host,source=/etc/resolv.conf \
          --mount volume=resolv,target=/etc/resolv.conf --volume modprobe,kind=host,source=/usr/sbin/modprobe \
          --mount volume=modprobe,target=/usr/sbin/modprobe \
          --volume lib-modules,kind=host,source=/lib/modules \
          --mount volume=lib-modules,target=/lib/modules \
          --uuid-file-save=/var/run/kubelet-pod.uuid"
        Environment="HTTP_PROXY={{ (cluster_variable "http_proxy") }}"
        Environment="HTTPS_PROXY={{ (cluster_variable "https_proxy") }}"
        Environment="NO_PROXY=localhost,127.0.0.1,.{{ (cluster_variable "cluster_name") }},{{ (cluster_variable "bootstrapper1_ip") }},{{ (cluster_variable "bootstrapper2_ip") }},{{ (cluster_variable "bootstrapper3_ip") }}"
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --api-servers=https://{{ (cluster_variable "bootstrapper1_ip") }}:4443,https://{{ (cluster_variable "bootstrapper2_ip") }}:4443,https://{{ (cluster_variable "bootstrapper3_ip") }}:4443 \
          --register-node=true \
          --allow-privileged=true \
          --config=/etc/kubernetes/manifests \
          --node-ip={{.IP}} \
          --cluster-dns={{(cluster_variable "dns_server_ip")}} \
          --cluster-domain={{ (cluster_variable "cluster_name") }} \
          --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml
        Restart=always
        RestartSec=10
        [Install]
        WantedBy=multi-user.target
