apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: ${BLACKSMITH_HYPERKUBE_IMAGE}
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --insecure-bind-address=${BLACKSMITH_MASTER_IP}
    - --etcd-servers=http://${BLACKSMITH_MASTER_IP}:4001,http://${BLACKSMITH_SECOND_IP}:4001,http://${BLACKSMITH_THIRD_IP}:4001
    - --allow-privileged=true
    - --service-cluster-ip-range=${SERVICE_IP_RANGE}
    - --secure-port=443
    - --advertise-address=${BLACKSMITH_MASTER_IP}
    - --admission-control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
    - --tls-cert-file=${MASTER_CERT}
    - --tls-private-key-file=${MASTER_KEY}
    - --client-ca-file=${CA_CERT}
    - --token-auth-file=${KNOWN_TOKENS}
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /srv/kubernetes
      name: srvkube
      readOnly: true
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
  volumes:
  - hostPath:
      path: /srv/kubernetes
    name: srvkube
  - hostPath:
      path: /etc/ssl
    name: etcssl
